### ISSUE TITLE
Erro ao rodar o comando `gulp`

### ISSUE THREAD

**Issue by gabrielfgularte** [BarraJS/site_barrajs#11]
Ao rodar `gulp` na linha de comando, o seguinte erro é printado no output:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'gulp-stylus'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/gabriel/projects/site_barrajs/gulpfile.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by danilorb** [comment]
Erro já resolvido.
Foi ajustado o gulpfile.
